cleanup css files
DACCS-Climate/marble-website pull request #102
Opened 2024-04-18 14:39 UTC by mishaschwartz

- merged css into a single file
   - there was actually only a single css class still in use in daccs-css.css so I really just moved that one
- removed unused css classes
- removed css custom property that referred to redoak directly (also was unused)
- fixed html so that we don't need .h3 and .h5 classes
- marked some css classes as unused but did not remove them yet:
   - @alexandercyu please review these ones and let me know whether they were kept around intentionally so that they could be used later if needed or if they should be removed as well.

2024-04-18 15:31 UTC, alexandercyu requested changes

2024-04-18 15:34 UTC, mishaschwartz commented on static/css/marble.css
> -
Where are they being used? Did I miss something?

2024-04-18 19:45 UTC, alexandercyu commented on static/css/marble.css
> -
It's in my branch that I am currently working on.  I don't know if you want to delete something that will be added back in later.

2024-04-19 19:42 UTC, alexandercyu commented
> @alexandercyu what about the other css classes that I've marked as _unused_?

If the class name is in the Figma design, leave it in the css file.  Regarding the extra "leading-text-1" I added, it's because the "subtitle-1" class can also be used for leading text/ lead-in text.

2024-04-19 19:44 UTC, alexandercyu approved these changes

2024-04-19 20:01 UTC, merged