Website cosmetic changes
DACCS-Climate/marble-website pull request #121
Opened 2024-05-02 15:06 UTC by alexandercyu

Fixes #118 #120 
- Add drop shadow to banner text
- Changed padding around quickstart menu items to 30px
- Changed space  between quickstart underline and first menu item to 25px
- Added black opaque background to quickstart menu

2024-05-02 19:15 UTC, mishaschwartz requested changes

2024-05-02 20:05 UTC, ShrutiK100 reviewed
Spacing below forum needs to be removed.
Change padding to 40px
Current dimensions for Quickstart menu- 15px below "Quickstart" title , above the line.
25 px between the Title+line and menu items
20 px between each menu item 
Menu box should be Width-500px and height-400px

2024-05-06 20:03 UTC, alexandercyu commented on static/css/marble.css
> +    --black-opacity-0-30: rgba(0,0,0,0.30);
Renamed these to be more general.

2024-05-06 20:08 UTC, alexandercyu commented on static/css/marble.css
> +    --transparent: transparent;
It just seemed weird using a "background-" variable for non background use.  But I guess that doesn't matter under the hood.

Removed this variable.

2024-05-08 20:49 UTC, alexandercyu commented
> Spacing below forum needs to be removed. Change padding to 40px Current dimensions for Quickstart menu- 15px below "Quickstart" title , above the line. 25 px between the Title+line and menu items 20 px between each menu item Menu box should be Width-500px and height-400px

Changes made.

2024-05-09 15:21 UTC, alexandercyu commented
> > Fixes #118 #120
> > 
> > * Add drop shadow to banner text
> > * Changed padding around quickstart menu items to 30px
> > * Changed space  between quickstart underline and first menu item to 25px
> > * Added black opaque background to quickstart menu
> 
> Each menu item has its own adjustments. Please apply these adjustments on each menu item. display: flex; width: 192px; height: 47px; flex-direction: column; justify-content: center; flex-shrink: 0;
> 
> When you will click on each menu item in developer mode you will see code that needs to be applied on Menu title and each menu item. Same has be shared in the screenshot. <img alt="Screenshot 2024-05-09 at 9 49 09 AM" width="701" src="https://private-user-images.githubusercontent.com/161752175/329291502-7519ae71-832d-49eb-8202-0a82e902fd26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjc3MTYsIm5iZiI6MTcxNTI2NzQxNiwicGF0aCI6Ii8xNjE3NTIxNzUvMzI5MjkxNTAyLTc1MTlhZTcxLTgzMmQtNDllYi04MjAyLTBhODJlOTAyZmQyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxNTEwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYmMwNmZlODM5ZGJmOGUwNDE1YThhNjBjZGE1NzQwODJkODM5ZDE1YzY0MDUxYjEzODg4OGFlZmEyNjcwNzYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ww-7KzCEauRgX-gQccEN_bKxevhYu3DUDvbcNuKuAZA">

Applied these changes.

2024-05-09 17:42 UTC, ShrutiK100 requested changes
Have commented on the changes required

2024-05-10 15:59 UTC, mishaschwartz requested changes
Add some default space between the title and the quickstart menu. Right now, they are right up against each other when the screen width is small:

![image](https://github.com/DACCS-Climate/marble-website/assets/4380924/6d15be80-a293-4c57-9d19-38382edbc18c)

2024-05-10 19:11 UTC, alexandercyu commented
> Have commented on the changes required

I can't see your comments.  Did you make them in the files?

2024-05-10 21:22 UTC, alexandercyu commented
> Add some default space between the title and the quickstart menu. Right now, they are right up against each other when the screen width is small:
> 
> ![image](https://private-user-images.githubusercontent.com/4380924/329639543-6d15be80-a293-4c57-9d19-38382edbc18c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNzMyNTgsIm5iZiI6MTcxNTM3Mjk1OCwicGF0aCI6Ii80MzgwOTI0LzMyOTYzOTU0My02ZDE1YmU4MC1hMjkzLTRjNTctOWQxOS0zODM4MmVkYmMxOGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTBUMjAyOTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTc5OWNjYWZkMzIwNjZiMzE5YjFhNzYyNDVlMTYzYzEzNTk3MDk3NGJiNjkzZTFiNDhkZWVhNmRjMDMyMTBlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MPaj8Zjga1Jc7SD7YQG0x0ivks2WEcpHS1vOhSZZl8U)

Added 50px space between them

2024-05-14 14:40 UTC, ShrutiK100 reviewed
<img width="190" alt="Screenshot 2024-05-14 at 10 37 58 AM" src="https://github.com/DACCS-Climate/marble-website/assets/161752175/c1389cb3-5212-4080-8ba1-73f20df0a879">
Not sure why in the mobile view (screenshot shared) the Title "MARBLE" is placed on the left of the quick start menu. The tile needs to be above the Quickstart menu according to mobile design.

2024-05-14 17:57 UTC, mishaschwartz commented
@alexandercyu I'll review after conflicts are resolved

2024-05-14 18:06 UTC, alexandercyu commented
> @alexandercyu I'll review after conflicts are resolved

The Resolve conflict button is greyed out for me.  Do I have to resolve this locally?

2024-05-17 13:36 UTC, mishaschwartz requested changes
You're missing a closing brace somewhere in marble.css so the css file isn't loading properly.

2024-05-17 14:07 UTC, alexandercyu commented
> You're missing a closing brace somewhere in marble.css so the css file isn't loading properly.

Fixed the missing brace.

2024-05-17 17:08 UTC, mishaschwartz approved these changes

2024-05-17 20:05 UTC, ShrutiK100 requested changes
Add 50px between the Marble title and Quickstart menu . Remove the drop shadow on Marble text(only for mobile design
<img width="249" alt="Screenshot 2024-05-17 at 4 02 10 PM" src="https://github.com/DACCS-Climate/marble-website/assets/161752175/7ad099c3-424c-4473-a882-6d720097041b">
)

2024-05-17 20:39 UTC, alexandercyu commented
> Add 50px between the Marble title and Quickstart menu . Remove the drop shadow on Marble text(only for mobile design <img alt="Screenshot 2024-05-17 at 4 02 10 PM" width="249" src="https://private-user-images.githubusercontent.com/161752175/331718950-7ad099c3-424c-4473-a882-6d720097041b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NzgwNjgsIm5iZiI6MTcxNTk3Nzc2OCwicGF0aCI6Ii8xNjE3NTIxNzUvMzMxNzE4OTUwLTdhZDA5OWMzLTQyNGMtNDQ3My1hODgyLTZkNzIwMDk3MDQxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QyMDI5MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wN2Q1YzdmOGNkNzdkNzQ2NTZmYmMxNWM3ZDkzOGQyMWQyYWE5ZGQ0NDc1NmE3ZGRmOTUyZDNiODUzZDczZmRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S-pYa7AWaYTr2ngvzcrYsBUxBEcSC0BLoN_QEKxWL1A"> )
> 


Are you saying remove the drop shadow from the banner title and all quickstart menu text for mobile size only?  Keep the drop shadow on desktop sizes?

2024-05-21 13:18 UTC, ShrutiK100 requested changes
Looks good in mobile mode although in tablet screen size browser the title "Marble" is set to white colour. Please change it to the standard colour applied in mobile and browser.
<img width="670" alt="Screenshot 2024-05-21 at 9 15 20 AM" src="https://github.com/DACCS-Climate/marble-website/assets/161752175/bbc45ff1-b433-4dc5-ab17-4bc2ab5dc945">

Also noticed a text drop occurring on tablet screen size. 
<img width="791" alt="Screenshot 2024-05-21 at 9 24 28 AM" src="https://github.com/DACCS-Climate/marble-website/assets/161752175/29abd188-1864-4df0-a48e-dc8240c26ece">

2024-05-21 20:01 UTC, alexandercyu commented
> Looks good in mobile mode although in tablet screen size browser the title "Marble" is set to white colour. Please change it to the standard colour applied in mobile and browser. <img alt="Screenshot 2024-05-21 at 9 15 20 AM" width="670" src="https://private-user-images.githubusercontent.com/161752175/332440000-bbc45ff1-b433-4dc5-ab17-4bc2ab5dc945.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMjE4NzIsIm5iZiI6MTcxNjMyMTU3MiwicGF0aCI6Ii8xNjE3NTIxNzUvMzMyNDQwMDAwLWJiYzQ1ZmYxLWI0MzMtNGRjNS1hYjE3LTRiYzJhYjVkYzk0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxOTU5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2Q2NzdmZGE2MjY5ZDhhOTgyMTNkMzg0MjYyODM1OWViZjA5ZmVmOGFhZGMyOTY0NWFhYTBlMzNjYjkxZWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5D-OtG99HNlpiXj8bdcAui9y-LSKmnL7Pf6_bHZoA3s">
> 
> Also noticed a text drop occurring on tablet screen size. <img alt="Screenshot 2024-05-21 at 9 24 28 AM" width="791" src="https://private-user-images.githubusercontent.com/161752175/332442886-29abd188-1864-4df0-a48e-dc8240c26ece.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMjE4NzIsIm5iZiI6MTcxNjMyMTU3MiwicGF0aCI6Ii8xNjE3NTIxNzUvMzMyNDQyODg2LTI5YWJkMTg4LTE4NjQtNGRmMC1hNDhlLWRjODI0MGMyNmVjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxOTU5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjBjOTdmNGQ3MWMwOWQ1MWZkOTIwNDVmN2Q3ZmFjN2Y2NDYwZWY4NTI2NWE0ZmEwYThiMTQyYzU1OTMzMzFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ixZtrkpOR0jE41e9GbGnWPSLRIFx3YTxlN7LZQKxP80">

- Made the Marble title rainbow coloured like in the design.
- Fixed the quickstart title wrapping when transitioning between screen sizes
- Made Marble title h1 in tablet size.

2024-05-22 17:18 UTC, ShrutiK100 approved these changes
Looks good!

2024-05-22 17:30 UTC, merged