Fix font and spacing in node selection menu
DACCS-Climate/marble-website pull request #147
Opened 2024-05-29 17:20 UTC by alexandercyu

Fixes #139 
- Fix font and spacing between node selection menu items
- Change space between node selection menu items to 50px in tablet size

2024-05-29 19:03 UTC, mishaschwartz requested changes

2024-05-29 19:03 UTC, mishaschwartz commented on static/css/marble.css
> +    .margin-node-menu-item {
identical in all media widths

2024-05-29 20:01 UTC, alexandercyu commented
Moved repeated class out of media query.

2024-05-31 20:16 UTC, ShrutiK100 approved these changes

2024-06-03 13:47 UTC, mishaschwartz requested changes
There is currently no space between the node menu items on `sm` size

2024-06-03 15:48 UTC, alexandercyu commented
> There is currently no space between the node menu items on `sm` size

Fixed the spacing between node menu items on sm size.

Cleaned up" >=576px" media query.

2024-06-03 17:43 UTC, mishaschwartz approved these changes
This looks good.

It's a little difficult to review all the of the code cleanup since a lot of that doesn't seem related to this PR but as far as I can tell by looking at the UI it doesn't seem to break anything.

2024-06-03 17:47 UTC, merged

2024-06-03 17:52 UTC, alexandercyu commented
> This looks good.
> 
> It's a little difficult to review all the of the code cleanup since a lot of that doesn't seem related to this PR but as far as I can tell by looking at the UI it doesn't seem to break anything.

The cleanup was mostly to get rid of duplicates in the " >=576px" media query.  The differences I remember are the space between the node page heading and value statement, and the padding in the node services cards.