Check committee menu
DACCS-Climate/marble-website pull request #150
Opened 2024-05-29 18:34 UTC by alexandercyu

Fixes #143 

- move margins to their own class
- remove unneeded bootstrap margin in html
- remove width: 100% styling in html

2024-05-29 19:32 UTC, mishaschwartz approved these changes

2024-05-30 14:40 UTC, ShrutiK100 requested changes
Committee headings for web version needs to be H4. Looks good on Mobile version

2024-05-30 15:03 UTC, alexandercyu commented
> Committee headings for web version needs to be H4. Looks good on Mobile version

Changed the title in desktop to h4.

2024-05-30 15:29 UTC, ShrutiK100 approved these changes
Looks good!

2024-05-30 15:34 UTC, merged